import 'styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head';

import TransparentLayout from 'layouts/TransparentLayout';

import pipe from 'utils/pipe';

interface MyAppProps extends AppProps {
  Component: any;
}

function MyApp({ Component, pageProps }: MyAppProps) {
  const Layout = Component?.Layout || TransparentLayout;

  return <Layout>
    <Head>
      <title>Recetas Andinas || Challenge Nubimetrics</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://fonts.googleapis.com/css?family=Poppins&display=optional"
        rel="stylesheet"
      />
    </Head>

    <Component {...pageProps} />
  </Layout>
}

export default pipe()(MyApp);

